import { LegalLayout } from "./LegalLayout";

export default function LegalDisclaimer() {
  return (
    <LegalLayout title="Legal Disclaimer" updated="June 2026">
      <h2>1. Important Notice</h2>
      <p>
        Welcome to Lexigenz.com ("Platform"). By accessing, browsing, registering for, or using this website, mobile application, database, APIs, tools, word generation tools, word lists, vocabulary services, or any related products and services provided by Lexigenz.com ("we", "us", or "our"), you acknowledge that you have read, understood, and agree to be bound by this Legal Disclaimer, our Terms of Use, and Privacy Policy.
      </p>
      <p>If you do not agree with any provision contained herein, you must immediately discontinue use of the Platform.</p>

      <h2>2. Information Purposes Only</h2>
      <p>The Platform is intended solely for informational, educational, research, and reference purposes. The information available through the Platform, including but not limited to:</p>
      <ul>
        <li>Word generation results and vocabulary suggestions</li>
        <li>Definition and usage examples</li>
        <li>Writing prompts and phrase ideas</li>
        <li>Language learning aids and word-of-the-day content</li>
        <li>Word lists and linguistic reference materials</li>
      </ul>
      <p>is provided for general informational purposes only and should not be construed as professional writing or editorial advice, legal advice, medical advice, or financial or investment advice. Users should seek independent professional advice before making any important business, legal, creative, or other decisions.</p>

      <h2>3. No Recommendation</h2>
      <p>Nothing on this Platform constitutes an endorsement of a particular word, phrase, or writing style; a recommendation regarding how to use generated content; or a guarantee that generated text is correct, appropriate, or suitable for your needs. Any decisions made based on information obtained from the Platform are made solely at the user's own risk.</p>

      <h2>4. No Guarantee of Accuracy</h2>
      <p>
        While we endeavour to maintain accurate, complete, and current information, we make no representations or warranties regarding the accuracy, completeness, reliability, timeliness, availability, suitability, currency, or quality of any information presented on the Platform. Information may contain errors, omissions, inaccuracies, delays, outdated content, technical faults, or third-party reporting errors. Content may change without notice.
      </p>
      <p>We are under no obligation to update, correct, revise, or verify any information displayed on the Platform.</p>

      <h2>5. Content and Data Disclaimer</h2>
      <p>
        Content and word data may be sourced from dictionaries, public word lists, language APIs, third-party providers, and community contributions. Word generation and vocabulary outputs may vary depending on user input and system processing. Content may be approximate, indicative, or temporarily unavailable.
      </p>
      <p>Generated text is not guaranteed to be original, error-free, or suitable for publication. Users must independently verify the accuracy and appropriateness of all content before relying on it.</p>

      <h2>6. Generator and Analytics Disclaimer</h2>
      <p>The Platform provides word generators, vocabulary tools, phrase suggestion tools, writing prompts, and other analytical services. Results generated by such tools:</p>
      <ul>
        <li>Are estimates only, based on user-provided information</li>
        <li>May contain assumptions and are not guaranteed</li>
        <li>Should not be relied upon as professional advice</li>
      </ul>
      <p>Past outputs, assumptions, projections, and generated content do not guarantee future results. We accept no responsibility for decisions made using tool outputs.</p>

      <h2>7. Third-Party Content</h2>
      <p>The Platform includes third-party content, research, news feeds, hyperlinks, embedded services, external websites, and APIs. We do not control, endorse, verify, or assume responsibility for any third-party content. Users access third-party resources entirely at their own risk.</p>

      <h2>8. No Fiduciary Relationship</h2>
      <p>
        Use of the Platform does not create an advisory relationship, fiduciary relationship, brokerage relationship, agency relationship, partnership, or joint venture between the user and the Platform. Lexigenz.com is not a registered broker-dealer, investment adviser, financial planner, or any other type of regulated financial entity in any jurisdiction.
      </p>

      <h2>9. User Responsibility</h2>
      <p>Users acknowledge and agree that they are solely responsible for:</p>
      <ul>
        <li>Evaluating information and verifying data accuracy</li>
        <li>Conducting independent research</li>
        <li>Consulting qualified professionals</li>
        <li>Complying with applicable laws and regulations</li>
        <li>Assessing content suitability for intended use</li>
        <li>Managing their own risks</li>
      </ul>
      <p>The Platform shall not be responsible for any decisions made by users.</p>

      <h2>10. No Warranty</h2>
      <p>The Platform is provided on an "AS IS" and "AS AVAILABLE" basis. We expressly disclaim all warranties, including but not limited to merchantability, fitness for a particular purpose, accuracy, availability, reliability, non-infringement, and performance.</p>

      <h2>11. Changes to This Disclaimer</h2>
      <p>We reserve the right to amend, modify, update, or replace this Disclaimer at any time without prior notice. Continued use of the Platform following publication of changes constitutes acceptance of such changes.</p>

      <h2>12. Governing Law</h2>
      <p>This Disclaimer shall be governed by and interpreted in accordance with the laws of South Africa. Any disputes arising from the use of the Platform shall be subject to the exclusive jurisdiction of the courts of South Africa.</p>

      <h2>13. Contact Information</h2>
      <p>
        For questions regarding this Disclaimer, please contact:<br /><br />
        <strong>Lexigenz.com</strong><br />
        Email: <a href="mailto:hello@lexigenz.com">hello@lexigenz.com</a><br />
        Website: <a href="https://lexigenz.com">https://lexigenz.com</a>
      </p>

      <div className="mt-10 p-6 rounded-2xl border border-destructive/30 bg-destructive/5">
        <h3 className="font-bold text-base mb-2 text-foreground">Risk Warning</h3>
        <p className="text-sm text-muted-foreground m-0">
          Use of the Platform for plagiarism, defamation, harassment, or any unlawful or irregular activity is prohibited. Generated content is not a substitute for qualified professional advice, and users should not rely on the Site for illegal, unethical, or prohibited uses.
        </p>
      </div>
    </LegalLayout>
  );
}
